let data = [
   {
      "item":"http://www.wikidata.org/entity/Q15777",
      "itemLabel":"C",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/The%20C%20Programming%20Language%20logo.svg",
      "pr":"210.381"
   },
   {
      "item":"http://www.wikidata.org/entity/Q251",
      "itemLabel":"Java",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Logo-java-830x460.jpg",
      "pr":"187.241"
   },
   {
      "item":"http://www.wikidata.org/entity/Q2407",
      "itemLabel":"C++",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/ISO%20C%2B%2B%20Logo.svg",
      "pr":"168.048"
   },
   {
      "item":"http://www.wikidata.org/entity/Q28865",
      "itemLabel":"Python",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Python-logo-notext.svg",
      "pr":"123.831"
   },
   {
      "item":"http://www.wikidata.org/entity/Q2005",
      "itemLabel":"JavaScript",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Unofficial%20JavaScript%20logo%202.svg",
      "pr":"113.209"
   },
   {
      "item":"http://www.wikidata.org/entity/Q42478",
      "itemLabel":"Perl",
      "pr":"92.6542"
   },
   {
      "item":"http://www.wikidata.org/entity/Q59",
      "itemLabel":"PHP",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/PHP-logo.svg",
      "pr":"86.7935"
   },
   {
      "item":"http://www.wikidata.org/entity/Q165436",
      "itemLabel":"assembly language",
      "pr":"77.363"
   },
   {
      "item":"http://www.wikidata.org/entity/Q83303",
      "itemLabel":"Fortran",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Fortran%20acs%20cover.jpeg",
      "pr":"67.1015"
   },
   {
      "item":"http://www.wikidata.org/entity/Q2370",
      "itemLabel":"C#",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/C%20Sharp%20wordmark.svg",
      "pr":"64.3378"
   },
   {
      "item":"http://www.wikidata.org/entity/Q161053",
      "itemLabel":"Ruby",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Ruby%20logo.svg",
      "pr":"55.3961"
   },
   {
      "item":"http://www.wikidata.org/entity/Q47607",
      "itemLabel":"Structured Query Language",
      "pr":"54.2368"
   },
   {
      "item":"http://www.wikidata.org/entity/Q42979",
      "itemLabel":"BASIC",
      "pr":"52.6328"
   },
   {
      "item":"http://www.wikidata.org/entity/Q132874",
      "itemLabel":"Lisp",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Lisp-glossy-120.jpg",
      "pr":"50.6048"
   },
   {
      "item":"http://www.wikidata.org/entity/Q81571",
      "itemLabel":"Pascal",
      "pr":"48.1841"
   },
   {
      "item":"http://www.wikidata.org/entity/Q34010",
      "itemLabel":"Haskell",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Haskell-Logo.svg",
      "pr":"39.0326"
   },
   {
      "item":"http://www.wikidata.org/entity/Q206904",
      "itemLabel":"R",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/R%20logo.svg",
      "pr":"36.6552"
   },
   {
      "item":"http://www.wikidata.org/entity/Q154755",
      "itemLabel":"Ada",
      "pr":"35.4571"
   },
   {
      "item":"http://www.wikidata.org/entity/Q235086",
      "itemLabel":"Smalltalk",
      "pr":"34.262"
   },
   {
      "item":"http://www.wikidata.org/entity/Q218170",
      "itemLabel":"PostScript",
      "pr":"32.4059"
   },
   {
      "item":"http://www.wikidata.org/entity/Q131140",
      "itemLabel":"COBOL",
      "pr":"31.2486"
   },
   {
      "item":"http://www.wikidata.org/entity/Q188531",
      "itemLabel":"Objective-C",
      "pr":"30.2264"
   },
   {
      "item":"http://www.wikidata.org/entity/Q187560",
      "itemLabel":"Scheme",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Lambda%20lc.svg",
      "pr":"27.1894"
   },
   {
      "item":"http://www.wikidata.org/entity/Q2378",
      "itemLabel":"Visual Basic",
      "pr":"26.7611"
   },
   {
      "item":"http://www.wikidata.org/entity/Q81294",
      "itemLabel":"Mathematica",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Mathematica%20Logo.svg",
      "pr":"26.6279"
   },
   {
      "item":"http://www.wikidata.org/entity/Q849146",
      "itemLabel":"Common Lisp",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Lisplogo%20alien%20256.png",
      "pr":"25.1595"
   },
   {
      "item":"http://www.wikidata.org/entity/Q169411",
      "itemLabel":"Unified Modeling Language",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/UML%20logo.svg",
      "pr":"23.3559"
   },
   {
      "item":"http://www.wikidata.org/entity/Q188436",
      "itemLabel":"ALGOL",
      "pr":"21.4944"
   },
   {
      "item":"http://www.wikidata.org/entity/Q207316",
      "itemLabel":"Lua",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Lua-logo-nolabel.svg",
      "pr":"21.0198"
   },
   {
      "item":"http://www.wikidata.org/entity/Q259138",
      "itemLabel":"ECMAScript",
      "pr":"20.1536"
   },
   {
      "item":"http://www.wikidata.org/entity/Q460584",
      "itemLabel":"Scala",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/%D0%882.png",
      "pr":"20.147"
   },
   {
      "item":"http://www.wikidata.org/entity/Q223433",
      "itemLabel":"PL/I",
      "pr":"20.0032"
   },
   {
      "item":"http://www.wikidata.org/entity/Q37227",
      "itemLabel":"Go",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Go%20Logo%20Blue.svg",
      "pr":"19.9323"
   },
   {
      "item":"http://www.wikidata.org/entity/Q487378",
      "itemLabel":"Embarcadero Delphi",
      "pr":"19.3697"
   },
   {
      "item":"http://www.wikidata.org/entity/Q178817",
      "itemLabel":"ASP.NET",
      "pr":"18.9334"
   },
   {
      "item":"http://www.wikidata.org/entity/Q5288",
      "itemLabel":"Tool Command Language",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Tcl.svg",
      "pr":"18.7767"
   },
   {
      "item":"http://www.wikidata.org/entity/Q212587",
      "itemLabel":"OCaml",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/OCaml%20Logo.svg",
      "pr":"18.5985"
   },
   {
      "item":"http://www.wikidata.org/entity/Q189248",
      "itemLabel":"GNU Bash",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Gnu-bash-logo.svg",
      "pr":"18.3755"
   },
   {
      "item":"http://www.wikidata.org/entity/Q163468",
      "itemLabel":"Prolog",
      "pr":"18.0664"
   },
   {
      "item":"http://www.wikidata.org/entity/Q608276",
      "itemLabel":"Unreal Engine 4",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/UE%20Logo%20Black%20Centered.svg",
      "pr":"17.4002"
   },
   {
      "item":"http://www.wikidata.org/entity/Q296187",
      "itemLabel":"APL",
      "pr":"16.7701"
   },
   {
      "item":"http://www.wikidata.org/entity/Q2166735",
      "itemLabel":"ALGOL 68",
      "pr":"16.6632"
   },
   {
      "item":"http://www.wikidata.org/entity/Q32110",
      "itemLabel":"XSLT",
      "pr":"16.5098"
   },
   {
      "item":"http://www.wikidata.org/entity/Q319268",
      "itemLabel":"D",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/D%20Programming%20Language%20logo.svg",
      "pr":"16.4621"
   },
   {
      "item":"http://www.wikidata.org/entity/Q732089",
      "itemLabel":"Eiffel",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Eiffel%20logo.svg",
      "pr":"14.8749"
   },
   {
      "item":"http://www.wikidata.org/entity/Q840410",
      "itemLabel":"PowerShell",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/PowerShell%20Core%206.0%20icon.png",
      "pr":"14.6932"
   },
   {
      "item":"http://www.wikidata.org/entity/Q959549",
      "itemLabel":"shell script",
      "pr":"14.686"
   },
   {
      "item":"http://www.wikidata.org/entity/Q860654",
      "itemLabel":"ML",
      "pr":"14.3366"
   },
   {
      "item":"http://www.wikidata.org/entity/Q234657",
      "itemLabel":"ActionScript",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Farm-Fresh%20page%20white%20actionscript.png",
      "pr":"14.2284"
   },
   {
      "item":"http://www.wikidata.org/entity/Q209455",
      "itemLabel":"VHDL",
      "pr":"14.1687"
   },
   {
      "item":"http://www.wikidata.org/entity/Q275472",
      "itemLabel":"Forth",
      "pr":"13.8343"
   },
   {
      "item":"http://www.wikidata.org/entity/Q334879",
      "itemLabel":"Erlang",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Erlang%20logo.svg",
      "pr":"13.6972"
   },
   {
      "item":"http://www.wikidata.org/entity/Q633894",
      "itemLabel":"Object Pascal",
      "pr":"12.6058"
   },
   {
      "item":"http://www.wikidata.org/entity/Q213970",
      "itemLabel":"AWK",
      "pr":"12.4963"
   },
   {
      "item":"http://www.wikidata.org/entity/Q1201810",
      "itemLabel":"Microsoft BASIC",
      "pr":"12.2534"
   },
   {
      "item":"http://www.wikidata.org/entity/Q827773",
      "itemLabel":"Verilog",
      "pr":"11.9585"
   },
   {
      "item":"http://www.wikidata.org/entity/Q51798",
      "itemLabel":"Clojure",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Clojure%20logo.svg",
      "pr":"11.0799"
   },
   {
      "item":"http://www.wikidata.org/entity/Q223679",
      "itemLabel":"GNU Octave",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Gnu-octave-logo.svg",
      "pr":"11.0278"
   },
   {
      "item":"http://www.wikidata.org/entity/Q810009",
      "itemLabel":"BCPL",
      "pr":"10.9815"
   },
   {
      "item":"http://www.wikidata.org/entity/Q756100",
      "itemLabel":"Node.js",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Node.js%20logo.svg",
      "pr":"10.8339"
   },
   {
      "item":"http://www.wikidata.org/entity/Q777358",
      "itemLabel":"Modula-2",
      "pr":"10.7168"
   },
   {
      "item":"http://www.wikidata.org/entity/Q479833",
      "itemLabel":"batch file",
      "pr":"10.5122"
   },
   {
      "item":"http://www.wikidata.org/entity/Q344266",
      "itemLabel":"Active Server Pages",
      "pr":"10.4999"
   },
   {
      "item":"http://www.wikidata.org/entity/Q597330",
      "itemLabel":"Standard ML",
      "pr":"10.4798"
   },
   {
      "item":"http://www.wikidata.org/entity/Q844595",
      "itemLabel":"Bourne shell",
      "pr":"10.3355"
   },
   {
      "item":"http://www.wikidata.org/entity/Q648619",
      "itemLabel":"FSharp",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Fsharp%20logo.png",
      "pr":"10.0829"
   },
   {
      "item":"http://www.wikidata.org/entity/Q212569",
      "itemLabel":"Simula",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Simula%20-%20logo.svg",
      "pr":"10.0753"
   },
   {
      "item":"http://www.wikidata.org/entity/Q681360",
      "itemLabel":"OpenCL",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/OpenCL.jpg",
      "pr":"9.92079"
   },
   {
      "item":"http://www.wikidata.org/entity/Q1209759",
      "itemLabel":"ALGOL 60",
      "pr":"9.86105"
   },
   {
      "item":"http://www.wikidata.org/entity/Q16340",
      "itemLabel":"XPath",
      "pr":"9.71976"
   },
   {
      "item":"http://www.wikidata.org/entity/Q685820",
      "itemLabel":"REXX",
      "pr":"9.68107"
   },
   {
      "item":"http://www.wikidata.org/entity/Q13743",
      "itemLabel":"Visual Basic Script",
      "pr":"9.52324"
   },
   {
      "item":"http://www.wikidata.org/entity/Q129137",
      "itemLabel":"AppleScript",
      "pr":"9.44582"
   },
   {
      "item":"http://www.wikidata.org/entity/Q17118377",
      "itemLabel":"Swift",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Swift%20logo%20with%20text.svg",
      "pr":"9.16101"
   },
   {
      "item":"http://www.wikidata.org/entity/Q477690",
      "itemLabel":"CUDA",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/CUDA.png",
      "pr":"8.63125"
   },
   {
      "item":"http://www.wikidata.org/entity/Q667566",
      "itemLabel":"Visual Basic for Applications",
      "pr":"8.51373"
   },
   {
      "item":"http://www.wikidata.org/entity/Q850661",
      "itemLabel":"XQuery",
      "pr":"8.46367"
   },
   {
      "item":"http://www.wikidata.org/entity/Q201436",
      "itemLabel":"Logo",
      "pr":"8.36551"
   },
   {
      "item":"http://www.wikidata.org/entity/Q504453",
      "itemLabel":"Groovy",
      "image":"http://commons.wikimedia.org/wiki/Special:FilePath/Groovy-logo.svg",
      "pr":"8.06837"
   },
   {
      "item":"http://www.wikidata.org/entity/Q297868",
      "itemLabel":"x86 assembly language",
      "pr":"7.92081"
   },

  {
     "item":"http://www.wikidata.org/entity/Q244627",
     "itemLabel":"Brainfuck",
     "pr":"3.54834"
  },
  {
     "item":"http://www.wikidata.org/entity/Q670180",
     "itemLabel":"Unlambda",
     "pr":"2.11193"
  },
  {
     "item":"http://www.wikidata.org/entity/Q1054365",
     "itemLabel":"INTERCAL",
     "pr":"2.03272"
  },
  {
     "item":"http://www.wikidata.org/entity/Q378222",
     "itemLabel":"Whitespace",
     "pr":"1.1741"
  },
  {
     "item":"http://www.wikidata.org/entity/Q517956",
     "itemLabel":"Malbolge",
     "pr":"0.98773"
  },
  {
     "item":"http://www.wikidata.org/entity/Q513238",
     "itemLabel":"LOLCODE",
     "image":"http://commons.wikimedia.org/wiki/Special:FilePath/LOLCode%20logo.png",
     "pr":"0.881297"
  },
  {
     "item":"http://www.wikidata.org/entity/Q814269",
     "itemLabel":"Befunge",
     "pr":"0.861429"
  },
  {
     "item":"http://www.wikidata.org/entity/Q3154138",
     "itemLabel":"Iota and Jot",
     "pr":"0.778285"
  },
  {
     "item":"http://www.wikidata.org/entity/Q3526013",
     "itemLabel":"Thue",
     "pr":"0.602189"
  },
  {
     "item":"http://www.wikidata.org/entity/Q359122",
     "itemLabel":"chef",
     "pr":"0.15"
  },
  {
     "item":"http://www.wikidata.org/entity/Q1140574",
     "itemLabel":"Shakespeare",
     "pr":"0.15"
  },
  {
     "item":"http://www.wikidata.org/entity/Q1886145",
     "itemLabel":"Piet",
     "pr":"0.15"
  },
  {
     "item":"http://www.wikidata.org/entity/Q17326337",
     "itemLabel":"GolfScript",
     "pr":"0.15"
  }
]

const BLACKLIST = [
  "Unified Modeling Language",
  "ECMAScript",
  "PL/I",
  "Embarcadero Delphi",
  "Unreal Engine 4",
  "APL",
  "XSLT",
  "shell script",
  "VHDL",
  "AWK",
  "Microsoft BASIC",
  "BCPL",
  "Bourne shell",
  "batch file",
  "XPath",
  "REXX",
  "Visual Basic for Applications",
  "XQuery",
  "x86 assembly language",
  "ALGOL 60",
  "ALGOL 68",
  "Modula-2",
]


let newdata=[];
for(let item of data) {
  if(BLACKLIST.indexOf(item.itemLabel) == -1)
    newdata.push(item);
}
data = newdata;
